### ISSUE TITLE
ussd not working

### ISSUE THREAD

**Issue by saviour123** [babca/python-gsmmodem#56]
Is there anyone here who is successful sending and receiving ussd?

```
$ python ussd_demo.py 
Initializing modem...
Sending USSD string: *123#
Traceback (most recent call last):
  File "ussd_demo.py", line 41, in <module>
    main()
  File "ussd_demo.py", line 30, in main
    response = modem.sendUssd("*123") # response type: gsmmodem.modem.Ussd
  File "/home/sav/.local/lib/python2.7/site-packages/gsmmodem/modem.py", line 963, in sendUssd
    cusdResponse = self.write('AT+CUSD=1,"{0}",15'.format(ussdString), timeout=responseTimeout) # Should respond with "OK"
  File "/home/sav/.local/lib/python2.7/site-packages/gsmmodem/modem.py", line 488, in write
    raise CommandError(data)
gsmmodem.exceptions.CommandError: AT+CUSD=1,"*123",15

```

**Comment by babca** [comment]
Your modem returns `ERROR` instead of `OK`, could you uncomment line 25 in `ussd_demo.py` (`logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.DEBUG)`)
and post here the whole communication log?
Which modem do you use?
