### ISSUE TITLE
Timeout exception thrown when a long message with non-English chars included

### ISSUE THREAD

**Issue by CyberBaby** [babca/python-gsmmodem#9]
Hi, nice to see the project live again.

I found that when i send the message to the modem with a long message with different language, English + Non-English, 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/var/www/gsmmodem/modem.py", line 1093, in __threadedHandleModemNotification
    self._handleSmsReceived(line)
  File "/var/www/gsmmodem/modem.py", line 1254, in _handleSmsReceived
    sms = self.readStoredSms(msgIndex, msgMemory)
  File "/var/www/gsmmodem/modem.py", line 1324, in readStoredSms
    msgData = self.write('AT+CMGR={0}'.format(index))
  File "/var/www/gsmmodem/modem.py", line 465, in write
    responseLines = super(GsmModem, self).write(data + writeTerm, waitForResponse=waitForResponse, timeout=timeout, expectedResponseTermSeq=expectedResponseTermSeq)
  File "/var/www/gsmmodem/serial_comms.py", line 144, in write
    raise TimeoutException()
TimeoutException: None

It seems that nth can be read in the _readLoop and thus the timeout. Any ideas?

**Comment by tomchy** [comment]
How long messages should I use in order to reproduce this issue?

I remember that I had a similar problem, but the currently used timeout values should be huge enough to send any reasonably long message. 
You may also try to increase them (or make an improvement and make them dependant on the message length). Lines that should be changed may be found in the following diff: https://github.com/babca/python-gsmmodem/commit/e3875305958136e2dc10bb6bea750976d4d9b4f5
